### ISSUE TITLE
FES: When FES is enabled, the pre_get_posts method causes PHP notices

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/edd-hide-download#14]
Our `pre_get_posts` method is calling `is_page` too early, as the query object hasn't been fully loaded just yet. We need to change to something similar to this:
```
			if ( function_exists( 'EDD_FES' ) ) {
				// if a download is hidden, prevent it from being hidden on the FES vendor dashboard page
				$vendor_page = EDD_FES()->helper->get_option( 'fes-vendor-dashboard-page', false );
				if ( ! empty( $query->query_vars['page_id'] ) && ! empty( $vendor_page ) && $vendor_page === $query->query_vars['page_id'] ) {
					return;
				}
			}
```

**Comment by ashleyfae** [comment]
I'm actually not getting any notices. Can anyone else reproduce this?

**Comment by robincornett** [comment]
I'm not getting notices on the vendor dashboard page, but I am on the vendor store page. I'll put together a PR for it.
